apiVersion: v1
kind: Service
metadata:
  name: front-end
  labels:
    run: front-end-svc
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    run: front-end
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      run: front-end
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: front-end
    spec:
      containers:
      - name: front-end
        image: nginx
        ports:
        - containerPort: 80
