apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: deployment-clusterrole
rules:
- apiGroups: [""]
  resources: ["Deployment", "StatefulSet", "DaemonSet"]
  verbs: ["create"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cicd-token
  namespace: app-team1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cicd-clusterrole-binging
subjects:
- kind: ServiceAccount
  name: cicd-token
  namespace: app-team1
roleRef:
  kind: ClusterRole
  name: deployment-clusterrole
  apiGroup: rbac.authorization.k8s.io
# ---
# # kubectl create rolebinding my-sa-view --clusterrole=view --serviceaccount=my-namespace:my-sa --namespace=my-namespace
# #
# # kubectl create clusterrolebinding my-binding --clusterrole=eagunu --serviceaccount=cicd:app-team1
# # # #################
# # kubectl create clusterrole test02 --verb=create --resource=Deployment,StatefulSet,DaemonSet
# # #######
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   # "namespace" omitted since ClusterRoles are not namespaced
#   name: deployment-clusterrole
# rules:
# - apiGroups: [""]
#   resources: ["Deployment", "StatefulSet", "DaemonSet"]
#   verbs: ["create"]
