# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: ci-cd-token08
#   namespace: app-team08
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: my-binding
# subjects:
# - kind: ServiceAccount
#   name: ci-cd-token08
#   apiGroup: ""
#   namespace: app-team08
# roleRef:
#   kind: ClusterRole
#   name: deploy08
#   apiGroup: ""
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: test08
subjects:
- kind: ServiceAccount
  name: ci-cd-token08
  apiGroup: ""
  namespace: app-team08
roleRef:
  kind: ClusterRole
  name: deploy08
  apiGroup: ""
