apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"sidecar","namespace":"default"},"spec":{"containers":[{"args":["/bin/sh","-c","i=0; while true; do\n  echo \"$i: $(date)\" \u003e\u003e /var/log/1.log;\n  echo \"$(date) INFO $i\" \u003e\u003e /var/log/2.log;\n  i=$((i+1));\n  sleep 1;\ndone\n"],"image":"busybox","name":"busybox-image","volumeMounts":[{"mountPath":"/var/log","name":"varlog"}]}],"volumes":[{"emptyDir":{},"name":"varlog"}]}}
  creationTimestamp: "2022-03-24T15:56:40Z"
  name: sidecar
  namespace: default
  resourceVersion: "304759"
  uid: 77f5223a-f6cf-4ba4-bb61-dac5cef21c46
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - |
      i=0; while true; do
        echo "$i: $(date)" >> /var/log/1.log;
        echo "$(date) INFO $i" >> /var/log/2.log;
        i=$((i+1));
        sleep 1;
      done
    image: busybox
    imagePullPolicy: Always
    name: busybox-image
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/log
      name: varlog
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-m6rm6
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gke-cka-default-pool-f29fb24a-6khd
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: varlog
  - name: kube-api-access-m6rm6
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-03-24T15:56:40Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-03-24T15:56:43Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-03-24T15:56:43Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-03-24T15:56:40Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://b86db20c0fb93e13158a39c7e82ae3be15be667189b93e7b1f3c6fc810af2955
    image: busybox:latest
    imageID: docker-pullable://busybox@sha256:caa382c432891547782ce7140fb3b7304613d3b0438834dce1cad68896ab110a
    lastState: {}
    name: busybox-image
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-03-24T15:56:42Z"
  hostIP: 10.142.0.6
  phase: Running
  podIP: 10.96.0.9
  podIPs:
  - ip: 10.96.0.9
  qosClass: BestEffort
  startTime: "2022-03-24T15:56:40Z"
