apiVersion: v1
kind: Service
metadata:
  name: front-back
  labels:
    run: front-back-svc
  namespace: cka
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    run: front-back
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-back
  namespace: cka
spec:
  replicas: 8
  selector:
    matchLabels:
      run: front-back
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: front-back
    spec:
      containers:
      - name: front-back
        image: nginx
        ports:
        - containerPort: 80
          name: http
      # nodeSelector:
      #    disk: ssd
