apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  nodeSelector:
    eagunu: papa
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx01
spec:
  containers:
  - name: nginx
    image: nginx
  nodeName: gke-cka-default-pool-816a0448-869x
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx02
spec:
  containers:
  - name: nginx
    image: nginx
  nodeName: gke-cka-default-pool-816a0448-869x
