apiVersion: v1
kind: Pod
metadata:
  name: web-server01
  #namespace: cka
spec:
  containers:
    - name: web-server-container
      image: nginx
      volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: app-pvc
