apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slow01
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  fstype: ext4
  replication-type: none

# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: standard
# provisioner: my.driver:wq

# ...
# allowVolumeExpansion: true
