---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebappdeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javawebapp
  template:
    metadata:
      name: javawebapp
      labels:
        app: javawebapp
    spec:
      containers:
      - name: javaweappcontainer
        image: dockerhandson/maven-web-application:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
             cpu: 100m
             memory: 150Mi
        # readinessProbe:
        #   httpGet:
        #     path: /java-web-app
        #     port: 8080
        #   initialDelaySeconds: 25
        #   timeoutSeconds: 1
        #   periodSeconds: 60
        # livenessProbe:
        #   httpGet:
        #     path: /java-web-app
        #     port: 8080
        #   initialDelaySeconds: 15
        #   timeoutSeconds: 1

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: javawebapp
# spec:
#   selector:
#     app: javawebapp
#   ports:
#   - port: 80
#     targetPort: 8080
#   type: LoadBalancer
